# Generated by Django 4.1.3 on 2022-11-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20, null=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('birthday', models.DateField(null=True)),
                ('phonenumber', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=10)),
                ('gate', models.CharField(max_length=10)),
                ('boarding_time', models.TimeField(null=True)),
                ('boarding_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'flight',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flightclass',
            fields=[
                ('flight_class', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flight_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('seat', models.CharField(max_length=10)),
                ('ticket_no', models.IntegerField()),
                ('date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'flight',
                'managed': False,
            },
        ),
    ]
