# Generated by Django 4.1.3 on 2022-12-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flightclass',
            table='flightclass',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
    ]
